# Generated by Django 6.0 on 2026-01-15 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True)),
                ('capacity', models.IntegerField(default=2)),
                ('price', models.DecimalField(decimal_places=2, help_text='Cena bazowa za noc', max_digits=10)),
                ('room_type', models.CharField(choices=[('single', 'Jednoosobowy'), ('double', 'Dwuosobowy'), ('suite', 'Apartament')], default='double', max_length=20)),
                ('status', models.CharField(choices=[('available', 'Wolny'), ('occupied', 'Zajęty'), ('dirty', 'Do sprzątania'), ('maintenance', 'W naprawie')], default='available', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('receptionist', 'Recepcjonista'), ('manager', 'Kierownik'), ('maid', 'Pokojówka')], default='receptionist', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GuestProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guest_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('number_of_guests', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Oczekująca'), ('confirmed', 'Potwierdzona'), ('checked_in', 'Zameldowany'), ('completed', 'Zakończona'), ('cancelled', 'Anulowana')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reservation_pin', models.CharField(blank=True, max_length=6, null=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='core.guestprofile')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='core.room')),
            ],
        ),
        migrations.CreateModel(
            name='SeasonPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('single', 'Jednoosobowy'), ('double', 'Dwuosobowy'), ('suite', 'Apartament')], max_length=20)),
                ('price_multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text='Mnożnik ceny bazowej (np. 1.5 dla +50%)', max_digits=4)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='core.season')),
            ],
        ),
    ]
