# Generated by Django 6.0 on 2026-01-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Gotówka'), ('online', 'Online')], default='cash', max_length=10),
        ),
    ]
