# Generated by Django 6.0 on 2026-01-16 08:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_reservation_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('payment_method', models.CharField(choices=[('cash', 'Gotówka'), ('card', 'Karta'), ('transfer', 'Przelew'), ('online', 'Online')], default='cash', max_length=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Oczekująca'), ('completed', 'Zrealizowana'), ('failed', 'Nieudana')], default='completed', max_length=10)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.reservation')),
            ],
        ),
    ]
