# Generated by Django 6.0 on 2025-12-27 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_reservation_number_of_guests_alter_employee_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('available', 'Dostępny'), ('occupied', 'Zajęty'), ('reserved', 'Zarezerwowany'), ('maintenance', 'W konserwacji'), ('to_clean', 'Do sprzątania')], default='available', max_length=30),
        ),
        migrations.CreateModel(
            name='RoomIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.guestprofile')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='core.room')),
            ],
            options={
                'verbose_name': 'Zgłoszona Usterka',
                'verbose_name_plural': 'Zgłoszone Usterki',
                'ordering': ['-created_at'],
            },
        ),
    ]
