# Generated by Django 6.0 on 2025-12-27 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_room_status_roomissue'),
    ]

    operations = [
        # Modele Season i SeasonPrice już istnieją w migracji 0001_initial
        # Ta migracja została pusta, ponieważ modele są już utworzone
    ]
