# Generated by Django 6.0 on 2025-12-27 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_room_status_roomissue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('identifier', models.CharField(max_length=50, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('priority', models.IntegerField(default=0, help_text='Wyższa wartość ma pierwszeństwo przy nakładających się sezonach')),
                ('apply_to_existing', models.BooleanField(default=False, help_text='Jeśli zaznaczone, po zapisie zastosuj ceny do przyszłych rezerwacji (pending/confirmed)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seasons_created', to='core.employee')),
            ],
            options={
                'verbose_name': 'Sezon / Cennik',
                'verbose_name_plural': 'Sezony / Cenniki',
                'ordering': ['-priority', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='SeasonPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('price_modifier_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Procentowa zmiana ceny bazowej (może być ujemna)', max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='season_prices', to='core.room')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='core.season')),
            ],
            options={
                'verbose_name': 'Cena w sezonie',
                'verbose_name_plural': 'Ceny w sezonach',
                'ordering': ['-season__priority', 'room__number'],
            },
        ),
    ]
