# Generated by Django 6.0 on 2026-01-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='role',
            field=models.CharField(choices=[('receptionist', 'Recepcjonista'), ('manager', 'Kierownik'), ('maid', 'Pokojówka'), ('technician', 'Pracownik techniczny')], default='receptionist', max_length=20),
        ),
    ]
