# Generated by Django 6.0 on 2025-12-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_season_seasonprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='pin_assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='pin',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
