# Generated by Django 6.0 on 2025-12-27 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_season_seasonprice'),
    ]

    operations = [
        # Pola pin_assigned_at i room.pin nie istnieją w modelach
        # Ta migracja została pusta
    ]
