# Generated by Django 6.0 on 2026-01-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_employeeprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='notes',
            field=models.TextField(blank=True, help_text='Notatki do rezerwacji (np. uszkodzenia, dodatkowe opłaty)', null=True),
        ),
    ]
